# Generated by Django 4.2.14 on 2024-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE'), ('unknown', 'Unknown')], default='unknown', max_length=15)),
            ],
        ),
    ]
